# Pandas Basics

This week we will work with the `pandas` library for data analysis.
The reference guide for numpy can be found here: https://pandas.pydata.org/docs/. 

In [17]:
import numpy as np
import pandas as pd
from random import randint
import os


# Pandas Series

Let's start by creating a series of some data. As labels are not specified here, the indexes will be integers by default.

In [86]:
import pandas as pd

# pd.Series(
#    data=None,
#    index=None,
#    dtype: 'Dtype | None' = None,
#    name=None,
#    copy: 'bool' = False,
#    fastpath: 'bool' = False,
#)

labels = ['a', 'b', 'c']
data = [10,50,100]
arr = np.array(data)
d = {'a': 10, 'b': '50', 'c': 100}

pd.Series(data)


#To utilise like a dictionary / hash table:
#ser1["a"]



0     10
1     50
2    100
dtype: int64

# More on Series

Now let's add some labels

In [87]:
labels = ['a', 'b', 'c']
data = [10,50,100]
arr = np.array(data)
d = {'a': 10, 'b': '50', 'c': 100}

series1 = pd.Series(data, labels, None, "Test series")
series1


a     10
b     50
c    100
Name: Test series, dtype: int64

In [88]:
data = [1,2,3,4]
labels = ['USA', 'China', 'Sweden', 'UK']

series2 = pd.Series(data, labels)
series2

USA       1
China     2
Sweden    3
UK        4
dtype: int64

In [89]:
series3 = pd.Series([1,2,5,4],['USA','China','Italy','UK'])
series3

USA      1
China    2
Italy    5
UK       4
dtype: int64

# Concatenation of Series

Notice how the attempt to concatenate the values of the two previous series works for some values where there is alignment. But it doesn't work for all values where there is not alignment. Also notice how the data type changes to float.

In [90]:
series2 + series3

China     4.0
Italy     NaN
Sweden    NaN
UK        8.0
USA       2.0
dtype: float64

# DataFrames (+ Random number generation)

First let's generate some random numbers via the random module in numpy

Repeatedly run the cell below - what do you notice?

In [91]:
from random import randint
import numpy as np
import pandas as pd

from numpy.random import randn

np.random.seed(2000)

rnum = randint(1,100)
rarr = randn(5,4)

print(rnum)
print(rarr)

26
[[ 1.73673761  1.89791391 -2.10677342 -0.14891209]
 [ 0.58306155 -2.25923303  0.13723954 -0.70121322]
 [-0.62078008 -0.47961976  1.20973877 -1.07518386]
 [ 0.80691921 -0.29078347 -0.22094764 -0.16915604]
 [ 1.10083444  0.08251052 -0.00437558 -1.72255825]]


# Let's create a DataFrame

In [92]:
df = pd.DataFrame(randn(5,4), ['A','B','C','D','E'], ['W','X','Y','Z'])
df

W         X         Y         Z
A  1.057556 -2.517913 -1.910640  1.306455
B  0.424398 -0.469168 -1.006073 -0.921923
C  0.626405  0.357177 -0.018719  0.221171
D  0.698604  0.834510 -1.665638 -2.901440
E -0.048639 -0.045378  1.475334 -0.513693

# Select columns of the dataframe 

Like indexed structures we can get access to single columns, or multiple columns (if we pass in as an array).


In [93]:
df["W"]

A    1.057556
B    0.424398
C    0.626405
D    0.698604
E   -0.048639
Name: W, dtype: float64

In [94]:
df[["W", "Z"]]

W         Z
A  1.057556  1.306455
B  0.424398 -0.921923
C  0.626405  0.221171
D  0.698604 -2.901440
E -0.048639 -0.513693

# Select rows

In [95]:
df.loc['A']

W    1.057556
X   -2.517913
Y   -1.910640
Z    1.306455
Name: A, dtype: float64

# Select rows - can also access via the integer position
In this case, 2 would be the 3rd row - AKA 'Row C'

In [96]:
#i for integer - can get to the index position. 
#2 in this case is row 3 AKA row C
df.iloc[2]

W    0.626405
X    0.357177
Y   -0.018719
Z    0.221171
Name: C, dtype: float64

# Conditions

In [97]:
df['W'] > 0

A     True
B     True
C     True
D     True
E    False
Name: W, dtype: bool

In [98]:
df[['W', 'Y']] > 0

W      Y
A   True  False
B   True  False
C   True  False
D   True  False
E  False   True

In [99]:
boolser = df['W'] > 0
result = df[boolser]
result[['Y','X']]

Y         X
A -1.910640 -2.517913
B -1.006073 -0.469168
C -0.018719  0.357177
D -1.665638  0.834510

In [100]:
df[df['W']>0][['Y','X']]

Y         X
A -1.910640 -2.517913
B -1.006073 -0.469168
C -0.018719  0.357177
D -1.665638  0.834510

## Brackets are important here for removing series

In [101]:
df[ (df['W']>0) & (df['X'] > 0) ]

W         X         Y         Z
C  0.626405  0.357177 -0.018719  0.221171
D  0.698604  0.834510 -1.665638 -2.901440

In [102]:
df.reset_index()

index         W         X         Y         Z
0     A  1.057556 -2.517913 -1.910640  1.306455
1     B  0.424398 -0.469168 -1.006073 -0.921923
2     C  0.626405  0.357177 -0.018719  0.221171
3     D  0.698604  0.834510 -1.665638 -2.901440
4     E -0.048639 -0.045378  1.475334 -0.513693

# Add new column

In [103]:
newind = 'CA NY WY OR CO'.split()
df['States'] = newind
df

W         X         Y         Z States
A  1.057556 -2.517913 -1.910640  1.306455     CA
B  0.424398 -0.469168 -1.006073 -0.921923     NY
C  0.626405  0.357177 -0.018719  0.221171     WY
D  0.698604  0.834510 -1.665638 -2.901440     OR
E -0.048639 -0.045378  1.475334 -0.513693     CO

# Groupby 

Like SQL groupBy - aggregating data of rows in a column into a cell

![groupby](https://miro.medium.com/max/1400/0*m-puRNwcnUl5zZ4O)

In [104]:
# Below is a data dictionary - where each key in the dict refers to an array of data

data = {'Company': ['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
        'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
        'Sales': [200, 120, 340, 124, 243, 350]
       }


In [105]:
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [106]:
byComp = df.groupby('Company')

#call aggregate function
byComp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [107]:
byComp.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [108]:
byComp.sum().loc['FB']

Sales    593
Name: FB, dtype: int64

# Counting 


In [109]:
df.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [110]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [111]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

# Conditional counting 

Calling the count method will enable us to count the entirety of column. However, what happens when we want to count according to a criteria?

In [112]:
# let's start be examining what the loop 'counter' gives us.

for i in df:
    print(i)

Company
Person
Sales


### You can see above that the reference 'i' refers to the column headers
But how do we count the cells greater than a value? 

In [113]:
for i in df['Sales']:
    print(i)

200
120
340
124
243
350


# Now let's consider conditions across multiple rows

First, we need to use iloc to get to the cells for each row

In [84]:
#Use iloc to get to a row

print(df.iloc[0])

Company    GOOG
Person      Sam
Sales       200
Name: 0, dtype: object
Company       GOOG
Person     Charlie
Sales          120
Name: 1, dtype: object


In [117]:
#Use iloc to get to a cell of that row

print(df.iloc[0][0])
print(df.iloc[0][1])
print(df.iloc[0][2])

GOOG
Sam
200


In [119]:
print(df.iloc[:])

  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350


# Concatenation

In [ ]:
pd.concat([df1, df2, df3])

In [ ]:
pd.concat([df1, df2, df3], axis=1 )

# Merge

Similar to joins in SQL

In [2]:
left = pd.DataFrame({'key': ['K0','K1','K2','K3'],
                     'A'  : ['A0','A1','A2','A3'],
                     'B'  : ['B0','B1','B2','B3']})

right = pd.DataFrame({'key': ['K0','K1','K2','K3'],
                     'C'  : ['C0','C1','C2','C3'],
                     'D'  : ['D0','D1','D2','D3']})

In [3]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [4]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

# Inner join

the intersect 

![innerjoin](https://learn.microsoft.com/en-us/power-query/images/inner-join-operation.png)


In [5]:
pd.merge(left, right, how= 'inner', on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [20]:
left = pd.DataFrame({'key1': ['K0','K0','K1','K2'],
                     'key2': ['K0','K1','K0','K1'],
                      'A'  : ['A0','A1','A2','A3'],
                      'B'  : ['B0','B1','B2','B3']})

right = pd.DataFrame({'key1': ['K0','K1','K1','K2'],
                      'key2': ['K0','K0','K0','K0'],
                       'C'  : ['C0','C1','C2','C3'],
                       'D'  : ['D0','D1','D2','D3']})

In [21]:
pd.merge(left, right, on=['key1','key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

# Outer join

![outerjoins](https://www.ionos.co.uk/digitalguide/fileadmin/DigitalGuide/Screenshots_2018/Outer-Join.jpg)

In [22]:
pd.merge(left, right, how= 'outer', on=['key1','key2'])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [23]:
pd.merge(left, right, how= 'right', on=['key1','key2'])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [24]:
pd.merge(left, right, how= 'left', on=['key1','key2'])

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

# Joining 

Similar to merge, but will join on the index, rather than the column



In [25]:
left = pd.DataFrame({'A'  : ['A0','A1','A2','A3'],
                     'B'  : ['B0','B1','B2','B3']},
                    index = ['K0','K1','K2','K3'])

right = pd.DataFrame({'C'  : ['C0','C1','C2','C3'],
                     'D'  : ['D0','D1','D2','D3']},
                    index = ['K0','K1','K2','K3'])

In [26]:
left.join(right)

A   B   C   D
K0  A0  B0  C0  D0
K1  A1  B1  C1  D1
K2  A2  B2  C2  D2
K3  A3  B3  C3  D3

# Smaller Sample Size

Pandas also has sample method, which returns a random and more manageable selection of rows to analyse.

In [33]:

df = pd.DataFrame(np.random.randn(5,4), ['A','B','C','D','E'], ['W','X','Y','Z'])

df.sample(1)

W         X        Y         Z
A -1.427129 -0.444422  1.09306  1.553331

# Check for null values



In [34]:
df.isna().sum()

W    0
X    0
Y    0
Z    0
dtype: int64

# Joining columns in a custom dataframe



In [35]:
first_t = df['W']
end_t = df['Z']
pd.concat([first_t, end_t], axis=1)

W         Z
A -1.427129  1.553331
B  0.595181  1.528626
C  0.534149  0.213717
D  1.463178 -0.775654
E  0.000466  0.881337