## List of tuples and `for` loop

In [1]:
metropolitan_areas = [
    # (city, country, population, area)
    ('Tokyo', 'Japan', 37400068, 13452),
    ('Delhi', 'India', 28514000, 3483),
    ('Shanghai', 'China', 25582000, 6341),
    ('São Paulo', 'Brasil', 21650000, 7947),
    ('Mexico City', 'Mexico', 21581000, 7866),
    ('Mumbai', 'India', 24400000, 4355),
    ('Cairo', 'Egypt', 20076000, 9844),
    ('Bejing', 'China', 19618000, 1334)
]

In [2]:
tokyo = metropolitan_areas[0]

In [3]:
tokyo

('Tokyo', 'Japan', 37400068, 13452)

In [10]:
for city_tuple in metropolitan_areas:
    print(f"City {city_tuple[0]}. Country {city_tuple[1]}. Population {city_tuple[2]}")

City Tokyo. Country Japan. Population 37400068
City Delhi. Country India. Population 28514000
City Shanghai. Country China. Population 25582000
City São Paulo. Country Brasil. Population 21650000
City Mexico City. Country Mexico. Population 21581000
City Mumbai. Country India. Population 24400000
City Cairo. Country Egypt. Population 20076000
City Bejing. Country China. Population 19618000


In [11]:
for city, country, population, area in metropolitan_areas:
    print(f"City {city}. Country {country}. Population {population}")

City Tokyo. Country Japan. Population 37400068
City Delhi. Country India. Population 28514000
City Shanghai. Country China. Population 25582000
City São Paulo. Country Brasil. Population 21650000
City Mexico City. Country Mexico. Population 21581000
City Mumbai. Country India. Population 24400000
City Cairo. Country Egypt. Population 20076000
City Bejing. Country China. Population 19618000


### Tuple unpacking

In [8]:
city, country, *_ = tokyo

In [9]:
_

[37400068, 13452]

## Iterables and the `zip` function:

In [12]:
cities = ['London', 'Manchester', 'Paris', 'Rome', 'Moscow']
countries = ['UK', 'UK', 'France', 'Italy', 'Russia']

In [26]:
z = zip(cities, countries)

In [31]:
next(z)

('Moscow', 'Russia')

### Slicing

In [32]:
ll = [1, 3, 5, 5.5, 8, 0, 8, 1, 200]

In [40]:
ll[1:-1:1]

[3, 5, 5.5, 8, 0, 8, 1]

In [41]:
my_string = "Hello, world"

In [46]:
reversed_ = my_string[::-1]

In [47]:
reversed_

'dlrow ,olleH'

In [48]:
my_string

'Hello, world'

### Dictionaries

In [49]:
my_dict = {}

In [50]:
type(my_dict)

dict

In [51]:
my_dict = {
    "London": "UK",
    "Rome": "Italy",
    "Manchester": "UK"
}

In [52]:
my_dict["London"]

'UK'

In [53]:
my_dict["Amsterdam"]

KeyError: 'Amsterdam'

In [54]:
my_dict.get("Amsterdam", "Don't know!")

"Don't know!"

In [55]:
my_dict["Amsterdam"] = "Netherlands"

In [56]:
my_dict

{'London': 'UK',
 'Rome': 'Italy',
 'Manchester': 'UK',
 'Amsterdam': 'Netherlands'}

In [63]:
for city, country in my_dict.items():
    print(f"City: {city}, country: {country}")

City: London, country: UK
City: Rome, country: Italy
City: Manchester, country: UK
City: Amsterdam, country: Netherlands


In [64]:
cities = ['London', 'Manchester', 'Paris', 'Rome', 'Moscow']
countries = ['UK', 'UK', 'France', 'Italy', 'Russia']
dict(zip(cities, countries))

{'London': 'UK',
 'Manchester': 'UK',
 'Paris': 'France',
 'Rome': 'Italy',
 'Moscow': 'Russia'}

# List comprehension

In [65]:
new_list = ['I', 5, 'am not', 5, True, 199, ['foo', 'baz'], 'foo', 'baz']
res = []
for el in new_list:
    res.append(type(el) == int)
    
res

[False, True, False, True, False, True, False, False, False]

In [67]:
res = [type(el) == int for el in new_list]

In [68]:
res

[False, True, False, True, False, True, False, False, False]

In [70]:
vec = [1.2, 1.6, -2, 3.2, -0.3, 5.6]

In [74]:
out = []
for el in vec:
    if el > 0.0:
        out.append(el**2)
out

[1.44, 2.5600000000000005, 10.240000000000002, 31.359999999999996]

In [76]:
out = [el**2 for el in vec]
out

[1.44, 2.5600000000000005, 4, 10.240000000000002, 0.09, 31.359999999999996]

In [78]:
[el**2 for el in vec if el > 0.0 and el < 2]

[1.44, 2.5600000000000005]

# Dict comprehension

In [83]:
{value: key for key, value in my_dict.items()}

{'UK': 'Manchester', 'Italy': 'Rome', 'Netherlands': 'Amsterdam'}

## Set

In [84]:
prime_numbers = {2, 3, 5, 7}

In [85]:
type(prime_numbers)

set

In [86]:
3 in prime_numbers

True

In [90]:
my_set = set()

In [91]:
type(my_set)

set

In [92]:
my_dict =  dict()

In [93]:
my_dict

{}

# NumPy Arrays

In [100]:
import numpy as np
from numpy import array

In [102]:
arr = array([1, 2, 3])

In [103]:
arr.ndim

1

In [104]:
arr.shape

(3,)

In [105]:
arr2d = array([[1, 2, 3], [5, 6, 7]])

In [106]:
arr2d.ndim

2

In [107]:
arr2d.shape

(2, 3)

In [108]:
arr2d.size

6

In [109]:
arr2d.dtype

dtype('int32')

In [114]:
arr2d = arr2d.astype("int8")

In [115]:
arr2d.dtype

dtype('int8')

In [116]:
arr2d = array([[1, 2, 3], [5, 6, 7.1]])

In [117]:
arr2d.dtype

dtype('float64')

In [120]:
arr = np.arange(0, 100, 2)

In [121]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [122]:
arr[5]

10

In [125]:
arr[5:20:2]

array([10, 14, 18, 22, 26, 30, 34, 38])

In [128]:
np.random.rand(10, 10)

array([[0.40315771, 0.65298148, 0.58320983, 0.15076144, 0.78339333,
        0.18609892, 0.79823533, 0.50068027, 0.93780162, 0.4909798 ],
       [0.48595885, 0.72187373, 0.9152771 , 0.51830494, 0.78811821,
        0.85085192, 0.05157694, 0.10765969, 0.32191001, 0.41867647],
       [0.79082972, 0.65152907, 0.73791853, 0.33752835, 0.48930645,
        0.06883518, 0.74878964, 0.2897128 , 0.18411377, 0.02347185],
       [0.63725519, 0.38234289, 0.21951761, 0.98614109, 0.69293948,
        0.20863357, 0.0820639 , 0.98999355, 0.82690179, 0.7486053 ],
       [0.16719025, 0.1789015 , 0.86662935, 0.77464151, 0.87745875,
        0.73013938, 0.56943945, 0.64701013, 0.38349405, 0.31222843],
       [0.69360063, 0.76260457, 0.44028309, 0.42575513, 0.91920334,
        0.90903604, 0.78831878, 0.64061289, 0.37957163, 0.16304567],
       [0.39918327, 0.16765764, 0.90072841, 0.9675971 , 0.17461595,
        0.049245  , 0.51980694, 0.35469365, 0.59318519, 0.65545182],
       [0.43890324, 0.25709917, 0.0907061